### ISSUE TITLE
SSL certificate not verified

### ISSUE THREAD

**Issue by Hatcher19** [rfunduk/rails-stripe-connect-example#10]
I am trying to setup the example app and i'm on the step - bin/rake app:setup. This is the error I get after I put in my client Id.

What is your application's development client ID? ***********************************
Checking client... rake aborted!
RestClient::SSLCertificateNotVerified: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

I'm guessing it doesn't like localhost:3000 for my development. I can add more of the trace if need be.

**Comment by rfunduk** [comment]
That's happening when trying to communicate with Stripe to check your Client ID: https://github.com/rfunduk/rails-stripe-connect-example/blob/master/lib/tasks/setup.rake#L79-L88

So it won't have anything to do with what host/port you're running the app on (the app is not running at all at this point). I'd say the problem is something do with your system's OpenSSL. Try doing the request `setup.rake` is doing by hand. Something like:

```
curl -I "https://connect.stripe.com/oauth/authorize?response_type=code&client_id=ca_YOUR_CLIENT_ID" | head
```

And see what happens, you should see something like:

```
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 15 Sep 2016 17:57:17 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 6491
Connection: keep-alive
```

If you get errors about SSL, then... yea :( something is wrong with your certs or similar.

**Comment by Hatcher19** [comment]
Ryan,

Thank for your quick response. SO i ran the code below and it gave me what you showed me but the problem is still there when I run bin/rake app:setup

Daniels-Laptop:rails-stripe-connect-example danielhatcher$ curl -I "https://connect.stripe.com/oauth/authorize?response_type=code&client_id=ca_9CCv9W3yDbGsopHsmqF8Qk0Vfnw2gJfP" | head
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  6316    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 15 Sep 2016 18:15:35 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 6316
Connection: keep-alive
Vary: Accept-Encoding
Set-Cookie: session=; domain=stripe.com; path=/; expires=Thu, 01-Jan-1970 00:00:00 GMT; secure
Set-Cookie: logged_in=; domain=stripe.com; path=/; expires=Thu, 01-Jan-1970 00:00:00 GMT; secure
Set-Cookie: login_as=; domain=stripe.com; path=/; expires=Thu, 01-Jan-1970 00:00:00 GMT; secure

---

Best Regards,

Daniel Hatcher

**Comment by rfunduk** [comment]
Ah, that's even more of a pain then, it sounds like your _ruby_ is the thing that is having SSL issues. As you can see in the code, it's simply using RestClient to make the same request you just did via curl. I'm not sure I can really help you with this, unfortunately. You could just not use the setup task and instead make your own `config/secrets.yml` (see `config/secrets.sample.yml` for the required values). But I doubt that will help since any time ruby goes to communicate with Stripe you'll likely run into this same problem.

**Comment by Hatcher19** [comment]
Ryan,

Hey I appreciate what you could help me with. IF and when I find a solution I will be sure to post the answer. Thank you again! Look forward to seeing what you have built haha

---

Best Regards,

Daniel Hatcher

**Comment by Hatcher19** [comment]
Here is what I did to get past this issue

rvm osx-ssl-certs update all

**Comment by rfunduk** [comment]
Great glad to hear you got it working 👍
